void onebin_xsec()
{
//=========Macro generated from canvas: c/c
//=========  (Tue Nov 27 10:21:47 2018) by ROOT version6.06/06
   TCanvas *c = new TCanvas("c", "c",0,0,500,888);
   gStyle->SetOptStat(0);
   c->SetHighLightColor(2);
   c->Range(-0.385621,-0.06329106,1.196078,1.673699);
   c->SetFillColor(10);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetLeftMargin(0.2438017);
   c->SetRightMargin(0.1239669);
   c->SetBottomMargin(0.1515789);
   c->SetFrameLineWidth(2);
   c->SetFrameBorderMode(0);
   c->SetFrameLineWidth(2);
   c->SetFrameBorderMode(0);
   
   TH1D *h_onebin_signalsignal_xsec_int_bnbcosmic__24 = new TH1D("h_onebin_signalsignal_xsec_int_bnbcosmic__24","",1,0,1);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->SetBinContent(1,0.8719318);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->SetBinError(1,0.002293816);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->SetMinimum(0.2);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->SetMaximum(1.5);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->SetEntries(144493.4);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->SetStats(0);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->SetFillColor(29);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#009900");
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->SetLineColor(ci);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->SetLineWidth(2);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetXaxis()->SetNdivisions(506);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetXaxis()->SetLabelFont(42);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetXaxis()->SetLabelSize(0);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetXaxis()->SetTitleSize(0.055);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetXaxis()->SetTickLength(0);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetXaxis()->SetTitleOffset(0.95);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetXaxis()->SetTitleFont(42);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetYaxis()->SetTitle("#LT#sigma#GT_{#phi} [10^{-38} cm^{2}]");
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetYaxis()->CenterTitle(true);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetYaxis()->SetDecimals();
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetYaxis()->SetNdivisions(506);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetYaxis()->SetLabelFont(42);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetYaxis()->SetLabelSize(0.05);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetYaxis()->SetTitleSize(0.07);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetYaxis()->SetTickLength(0.05);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetYaxis()->SetTitleOffset(1.24);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetYaxis()->SetTitleFont(42);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetZaxis()->SetNdivisions(506);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetZaxis()->SetLabelFont(42);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetZaxis()->SetTitleSize(0.055);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetZaxis()->SetTitleOffset(0.8);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->GetZaxis()->SetTitleFont(42);
   h_onebin_signalsignal_xsec_int_bnbcosmic__24->Draw("E2");
   
   TH1D *h_mc_main__25 = new TH1D("h_mc_main__25","",1,0,1);
   h_mc_main__25->SetBinContent(1,0.8719318);
   h_mc_main__25->SetBinError(1,0.002293816);
   h_mc_main__25->SetMinimum(0.2);
   h_mc_main__25->SetMaximum(1.5);
   h_mc_main__25->SetEntries(144493.4);
   h_mc_main__25->SetStats(0);

   ci = TColor::GetColor("#009900");
   h_mc_main__25->SetLineColor(ci);
   h_mc_main__25->SetLineWidth(2);
   h_mc_main__25->GetXaxis()->SetNdivisions(506);
   h_mc_main__25->GetXaxis()->SetLabelFont(42);
   h_mc_main__25->GetXaxis()->SetLabelSize(0);
   h_mc_main__25->GetXaxis()->SetTitleSize(0.055);
   h_mc_main__25->GetXaxis()->SetTickLength(0);
   h_mc_main__25->GetXaxis()->SetTitleOffset(0.95);
   h_mc_main__25->GetXaxis()->SetTitleFont(42);
   h_mc_main__25->GetYaxis()->SetTitle("#LT#sigma#GT_{#phi} [10^{-38} cm^{2}]");
   h_mc_main__25->GetYaxis()->CenterTitle(true);
   h_mc_main__25->GetYaxis()->SetDecimals();
   h_mc_main__25->GetYaxis()->SetNdivisions(506);
   h_mc_main__25->GetYaxis()->SetLabelFont(42);
   h_mc_main__25->GetYaxis()->SetLabelSize(0.05);
   h_mc_main__25->GetYaxis()->SetTitleSize(0.07);
   h_mc_main__25->GetYaxis()->SetTickLength(0.05);
   h_mc_main__25->GetYaxis()->SetTitleOffset(1.24);
   h_mc_main__25->GetYaxis()->SetTitleFont(42);
   h_mc_main__25->GetZaxis()->SetNdivisions(506);
   h_mc_main__25->GetZaxis()->SetLabelFont(42);
   h_mc_main__25->GetZaxis()->SetTitleSize(0.055);
   h_mc_main__25->GetZaxis()->SetTitleOffset(0.8);
   h_mc_main__25->GetZaxis()->SetTitleFont(42);
   h_mc_main__25->Draw("histo same");
   
   TH1D *h_onebin_signalsignal_xsec_int_bnbcosmic__26 = new TH1D("h_onebin_signalsignal_xsec_int_bnbcosmic__26","",1,0,1);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->SetBinContent(1,0.8258523);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->SetBinError(1,0.002396979);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->SetMinimum(0.2);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->SetMaximum(1.5);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->SetEntries(118707);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->SetStats(0);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->SetFillColor(38);

   ci = TColor::GetColor("#0000cc");
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->SetLineColor(ci);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->SetLineWidth(2);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetXaxis()->SetNdivisions(506);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetXaxis()->SetLabelFont(42);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetXaxis()->SetTitleSize(0.055);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetXaxis()->SetTitleOffset(0.8);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetXaxis()->SetTitleFont(42);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetYaxis()->SetTitle("#LT#sigma#GT_{#phi} [10^{-38} cm^{2}]");
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetYaxis()->CenterTitle(true);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetYaxis()->SetDecimals();
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetYaxis()->SetNdivisions(506);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetYaxis()->SetLabelFont(42);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetYaxis()->SetTitleSize(0.055);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetYaxis()->SetTitleOffset(0.9);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetYaxis()->SetTitleFont(42);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetZaxis()->SetNdivisions(506);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetZaxis()->SetLabelFont(42);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetZaxis()->SetTitleSize(0.055);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetZaxis()->SetTitleOffset(0.8);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->GetZaxis()->SetTitleFont(42);
   h_onebin_signalsignal_xsec_int_bnbcosmic__26->Draw("E2 same");
   
   TH1D *_h_alt_mc_xsec_main__27 = new TH1D("_h_alt_mc_xsec_main__27","",1,0,1);
   _h_alt_mc_xsec_main__27->SetBinContent(1,0.8258523);
   _h_alt_mc_xsec_main__27->SetBinError(1,0.002396979);
   _h_alt_mc_xsec_main__27->SetMinimum(0.2);
   _h_alt_mc_xsec_main__27->SetMaximum(1.5);
   _h_alt_mc_xsec_main__27->SetEntries(118707);
   _h_alt_mc_xsec_main__27->SetStats(0);

   ci = TColor::GetColor("#0000cc");
   _h_alt_mc_xsec_main__27->SetLineColor(ci);
   _h_alt_mc_xsec_main__27->SetLineWidth(2);
   _h_alt_mc_xsec_main__27->GetXaxis()->SetNdivisions(506);
   _h_alt_mc_xsec_main__27->GetXaxis()->SetLabelFont(42);
   _h_alt_mc_xsec_main__27->GetXaxis()->SetTitleSize(0.055);
   _h_alt_mc_xsec_main__27->GetXaxis()->SetTitleOffset(0.8);
   _h_alt_mc_xsec_main__27->GetXaxis()->SetTitleFont(42);
   _h_alt_mc_xsec_main__27->GetYaxis()->SetTitle("#LT#sigma#GT_{#phi} [10^{-38} cm^{2}]");
   _h_alt_mc_xsec_main__27->GetYaxis()->CenterTitle(true);
   _h_alt_mc_xsec_main__27->GetYaxis()->SetDecimals();
   _h_alt_mc_xsec_main__27->GetYaxis()->SetNdivisions(506);
   _h_alt_mc_xsec_main__27->GetYaxis()->SetLabelFont(42);
   _h_alt_mc_xsec_main__27->GetYaxis()->SetTitleSize(0.055);
   _h_alt_mc_xsec_main__27->GetYaxis()->SetTitleOffset(0.9);
   _h_alt_mc_xsec_main__27->GetYaxis()->SetTitleFont(42);
   _h_alt_mc_xsec_main__27->GetZaxis()->SetNdivisions(506);
   _h_alt_mc_xsec_main__27->GetZaxis()->SetLabelFont(42);
   _h_alt_mc_xsec_main__27->GetZaxis()->SetTitleSize(0.055);
   _h_alt_mc_xsec_main__27->GetZaxis()->SetTitleOffset(0.8);
   _h_alt_mc_xsec_main__27->GetZaxis()->SetTitleFont(42);
   _h_alt_mc_xsec_main__27->Draw("histo same");
   
   TH1D *h_syst_unc__28 = new TH1D("h_syst_unc__28","",1,0,1);
   h_syst_unc__28->SetBinContent(1,0.6931296);
   h_syst_unc__28->SetBinError(1,0.165229);
   h_syst_unc__28->SetEntries(4533.279);
   h_syst_unc__28->SetStats(0);
   h_syst_unc__28->SetLineWidth(2);
   h_syst_unc__28->SetMarkerStyle(20);
   h_syst_unc__28->SetMarkerSize(0.1);
   h_syst_unc__28->GetXaxis()->SetTitle(" Track length");
   h_syst_unc__28->GetXaxis()->SetNdivisions(506);
   h_syst_unc__28->GetXaxis()->SetLabelFont(42);
   h_syst_unc__28->GetXaxis()->SetTitleSize(0.055);
   h_syst_unc__28->GetXaxis()->SetTitleOffset(0.8);
   h_syst_unc__28->GetXaxis()->SetTitleFont(42);
   h_syst_unc__28->GetYaxis()->SetNdivisions(506);
   h_syst_unc__28->GetYaxis()->SetLabelFont(42);
   h_syst_unc__28->GetYaxis()->SetTitleSize(0.055);
   h_syst_unc__28->GetYaxis()->SetTitleOffset(0.9);
   h_syst_unc__28->GetYaxis()->SetTitleFont(42);
   h_syst_unc__28->GetZaxis()->SetNdivisions(506);
   h_syst_unc__28->GetZaxis()->SetLabelFont(42);
   h_syst_unc__28->GetZaxis()->SetTitleSize(0.055);
   h_syst_unc__28->GetZaxis()->SetTitleOffset(0.8);
   h_syst_unc__28->GetZaxis()->SetTitleFont(42);
   h_syst_unc__28->Draw("E1 X0 same");
   
   TH1D *h_data__29 = new TH1D("h_data__29","",1,0,1);
   h_data__29->SetBinContent(1,0.6931296);
   h_data__29->SetBinError(1,0.01029457);
   h_data__29->SetEntries(4533.279);
   h_data__29->SetStats(0);
   h_data__29->SetLineWidth(2);
   h_data__29->SetMarkerStyle(20);
   h_data__29->SetMarkerSize(0.6);
   h_data__29->GetXaxis()->SetTitle(" Track length");
   h_data__29->GetXaxis()->SetNdivisions(506);
   h_data__29->GetXaxis()->SetLabelFont(42);
   h_data__29->GetXaxis()->SetTitleSize(0.055);
   h_data__29->GetXaxis()->SetTitleOffset(0.8);
   h_data__29->GetXaxis()->SetTitleFont(42);
   h_data__29->GetYaxis()->SetNdivisions(506);
   h_data__29->GetYaxis()->SetLabelFont(42);
   h_data__29->GetYaxis()->SetTitleSize(0.055);
   h_data__29->GetYaxis()->SetTitleOffset(0.9);
   h_data__29->GetYaxis()->SetTitleFont(42);
   h_data__29->GetZaxis()->SetNdivisions(506);
   h_data__29->GetZaxis()->SetLabelFont(42);
   h_data__29->GetZaxis()->SetTitleSize(0.055);
   h_data__29->GetZaxis()->SetTitleOffset(0.8);
   h_data__29->GetZaxis()->SetTitleFont(42);
   h_data__29->Draw("E1 X0 same");
   
   TLegend *leg = new TLegend(0.25,0.7717265,0.4623288,0.8308227,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.035);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("h_onebin_signalsignal_xsec_int_bnbcosmic","GENIE Default + Emp. MEC (Stat. Unc.)","lpf");
   entry->SetFillColor(29);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#009900");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_onebin_signalsignal_xsec_int_bnbcosmic","GENIE Alternative (Stat. Unc.)","lpf");
   entry->SetFillColor(38);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000cc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_data","Data (Stat. #oplus Syst. Unc.)","ep");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(0.6);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.77,0.92,"MicroBooNE Preliminary");
tex->SetNDC();
   tex->SetTextAlign(32);

   ci = TColor::GetColor("#666666");
   tex->SetTextColor(ci);
   tex->SetTextSize(0.03959276);
   tex->SetLineWidth(2);
   tex->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
